apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: event-service
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: event-service
    spec:
      containers:
        - image: event-service-docker:event-service
          name: event-service-docker
          ports:
            - containerPort: 8095
          resources: {}
          imagePullPolicy: Never